### PR TITLE
Fix Editor breaking on invalid config

### LINKED ISSUE #395: Invalid json in config editor breaks editor

### PR DESCRIPTION
**Pull request by siddhant1**
Fixes #395

### CODE REVIEW

File: src/reducers/index.ts [hunk 1]
```diff
@@ -1,5 +1,5 @@
 import * as vl from 'vega-lite';
-import { Config } from 'vega-lite/src/config';
+// import { Config } from 'vega-lite/src/config';
```
Comment (domoritz) [inline src/reducers/index.ts]: delete
