### PR TITLE
Fix formatting spec bug

### LINKED ISSUE #88: Formatting bug
Hitting the format button multiple times formats again.

### PR DESCRIPTION
**Pull request by ydlamba**
Fixes #88.

### CODE REVIEW

File: src/components/input-panel/spec-editor/renderer.tsx [hunk 1]
```diff
@@ -127,7 +127,6 @@ class Editor extends React.Component<Props, State> {
       provideDocumentFormattingEdits(model, options, token) {
         return [
           {
-            range: model.getFullModelRange(),
```
Comment (ydlamba) [inline src/components/input-panel/spec-editor/renderer.tsx]: This is what a bug looks like. You never know where it is. :bug:
